version: '3.8'
services:
  web:
    build: .

    command:
      [
        "sh",
        "-c",
        "poetry run python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.api.main:app --reload --host 0.0.0.0 --port 8000",
      ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_USER}
      POSTGRES_DB: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
