version: '3.8'
services:
  web:
    build: .
    command: uvicorn src.smart_box.infrastructure.adapters.api.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
  db:
      image: postgres:latest
      environment:
        POSTGRES_DB: dbname
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
