version: '3.8'
services:
  web:
    build: .
    command: uvicorn src.app.entrypoint.api.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
  db:
      image: postgres:latest
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - "${POSTGRES_PODOCKERT}:${POSTGRES_PORT}"
      volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
