version: '3.8'
services:
  web:
    build: .
    command: uvicorn src.app.entrypoint.api.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
    env_file:
      - .env  # Path to your .env file relative to the compose file
  db:
      image: postgres:latest
      environment:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
      ports:
        - "${DB_PORT}:${DB_PORT}"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
volumes:
  postgres_data:
